andres' chickensexing.js method implemented
fjcoding/AT-BC-LAT-01 pull request #13
Opened 2021-07-13 20:03 UTC by ap102

I've completed the chickenSexing kata and uncommented the respective test :)

2021-07-13 21:25 UTC, J0c4 requested changes

2021-07-13 21:25 UTC, J0c4 commented on katas/chicken-sexing/andres/chickenSexing.js
> +    for(var i=0; i<bobsDecisions.length; i++){
Please add space between `for` and `(`, and for `<` operator. Also, please include space between `)` and `{`

2021-07-13 21:25 UTC, J0c4 commented on katas/chicken-sexing/andres/chickenSexing.js
> +        if (bobsDecisions[i]==expertDecisions[i]) {
Same here for `==`

2021-07-13 21:25 UTC, J0c4 commented on katas/chicken-sexing/andres/chickenSexing.js
> +    for(var i=0; i<bobsDecisions.length; i++){
A better name for `i` could be something like `index`

2021-07-13 21:25 UTC, J0c4 commented on katas/chicken-sexing/andres/chickenSexing.js
> +        }else if(bobsDecisions[i]=='?'||expertDecisions[i]=='?'){
Same here on spaces

2021-07-14 00:53 UTC, ap102 commented
I made the mistake to add the 'square-digits.test.js' file to the commit when I was working at the 'andres/square-digits' branch.
I would like to know if I could close this PR and open another without the 'square-digits.test.js' file.

2021-07-14 02:17 UTC, J0c4 commented
> I made the mistake to add the 'square-digits.test.js' file to the commit when I was working at the 'andres/square-digits' branch.
> I would like to know if I could close this PR and open another without the 'square-digits.test.js' file.

You can remove the file using `git rm katas/square-digits/andres/squareDigits.test.js`, commit that change and push it as a new commit in this same PR

2021-07-14 02:43 UTC, J0c4 commented
I reviewed your lates updates, those look good! just fix the problem with the file that is not expected and this should be ready to merge

2021-07-14 02:45 UTC, ap102 commented
That's good to know!, I'm sending the commit right now 🙂
________________________________
De: Jose Carlos ***@***.***>
Enviado: martes, 13 de julio de 2021 21:44
Para: fjcoding/AT-BC-LAT-01 ***@***.***>
Cc: Andres Pinzon Barragan ***@***.***>; Author ***@***.***>
Asunto: Re: [fjcoding/AT-BC-LAT-01] andres' chickensexing.js method implemented (#13)


I reviewed your lates updates, those look good! just fix the problem with the file that is not expected and this should be ready to merge

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/fjcoding/AT-BC-LAT-01/pull/13#issuecomment-879541792>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AU2LFMQZV3JOB5UPVU23BPLTXT2XRANCNFSM5AKA57PQ>.

2021-07-14 02:50 UTC, J0c4 approved these changes

2021-07-14 02:54 UTC, merged